import pandas as pd

HEADERS = {
    "ESSENCIAIS": [
        "ESCRITÓRIO",
        "CNPJ",
        "PARTE AUTORA",
        "PARTE RÉ",
        "PROCESSO",
        "UF",
        "DATA DA AÇÃO",
        "TIPO DE AÇÃO",
        "PRODUTO",
    ],
    "BH(ATIVAS)": [
        "ESCRITÓRIO",
        "CNPJ",
        "PARTE AUTORA",
        "PARTE RÉ",
        "CPF/CNPJ RÉ",
        "NÚMERO DO PROCESSO",
        "UF",
        "COMARCA",
        "JUÍZO",
        "DATA DA AÇÃO",
        "TIPO DE AÇÃO",
        "ASSUNTO",
        "LIMINAR",
        "VALOR DA CAUSA",
        "VALOR DO RISCO ATUALIZADO",
        "PROBABILIDADE DE PERDA",
        "HONORÁRIOS",
        "DEPÓSITOS BARI",
        "DEPÓSITOS ATUALIZADOS - BARI",
        "DEPÓSITOS - AUTORA",
        "ÚLTIMO ANDAMENTO PROCESSUAL",
        "PRODUTO",
        "OBSERVAÇÃO",
    ],
    "BH(PASSIVAS)": [
        "ESCRITÓRIO",
        "CNPJ",
        "PARTE AUTORA",
        "PARTE RÉ",
        "NÚMERO DO PROCESSO",
        "UF",
        "COMARCA",
        "JUÍZO",
        "DATA DA AÇÃO",
        "TIPO DE AÇÃO",
        "ASSUNTO",
        "LIMINAR",
        "VALOR DA CAUSA",
        "VALOR DO RISCO ATUALIZADO",
        "PROBABILIDADE DE PERDA",
        "HONORÁRIOS",
        "DEPÓSITOS BARI",
        "DEPÓSITOS ATUALIZADOS - BARI",
        "DEPÓSITOS - CLIENTE",
        "ÚLTIMO ANDAMENTO PROCESSUAL",
        "PRODUTO",
        "OBSERVAÇÃO",
    ],
    "SEC(ATIVAS)": [
        "ESCRITÓRIO",
        "CNPJ",
        "PARTE AUTORA",
        "PARTE RÉ",
        "CPF/CNPJ RÉ",
        "CRI",
        "NÚMERO DO PROCESSO",
        "UF",
        "COMARCA",
        "JUÍZO",
        "DATA DA AÇÃO",
        "TIPO DE AÇÃO",
        "ASSUNTO",
        "LIMINAR",
        "VALOR DA CAUSA",
        "VALOR DO RISCO ATUALIZADO",
        "PROBABILIDADE DE PERDA",
        "HONORÁRIOS",
        "DEPÓSITOS BARI",
        "DEPÓSITOS ATUALIZADOS - BARI",
        "DEPÓSITOS - AUTORA",
        "ÚLTIMO ANDAMENTO PROCESSUAL",
        "PRODUTO",
        "OBSERVAÇÃO",
    ],
    "SEC(PASSIVAS)": [
        "ESCRITÓRIO",
        "CNPJ",
        "PARTE AUTORA",
        "PARTE RÉ",
        "CRI",
        "NÚMERO DO PROCESSO",
        "UF",
        "COMARCA",
        "JUÍZO",
        "DATA DA AÇÃO",
        "TIPO DE AÇÃO",
        "ASSUNTO",
        "LIMINAR",
        "VALOR DA CAUSA",
        "VALOR DO RISCO ATUALIZADO",
        "PROBABILIDADE DE PERDA",
        "HONORÁRIOS",
        "DEPÓSITOS BARI",
        "DEPÓSITOS ATUALIZADOS - BARI",
        "DEPÓSITOS - CLIENTE",
        "ÚLTIMO ANDAMENTO PROCESSUAL",
        "PRODUTO",
        "OBSERVAÇÃO",
    ],
    "TRABALHISTAS": [
        "ESCRITÓRIO",
        "CNPJ ESCRITÓRIO",
        "PARTE AUTORA",
        "PARTE RÉ",
        "Nº PROCESSO",
        "UF",
        "COMARCA",
        "JUÍZO",
        "DATA DA AÇÃO",
        "TIPO DE AÇÃO",
        "ASSUNTO DA AÇÃO",
        "LIMINAR ATIVA",
        "VALOR ORIGINAL DO LITÍGIO",
        "VALOR DO RISCO ATUALIZADO",
        "PROBABILIDADE DE PERDA",
        "HONORÁRIOS DE ÊXITO",
        "DEPÓSITOS RECLAMANTE",
        "DEPÓSITO RECURSO ORDINÁRIO",
        "DEPÓSITO RECURSO DE REVISTA",
        "GARANTIA DO JUÍZO",
        "DEPÓSITOS BARI",
        "ÚLTIMO ANDAMENTO PROCESSUAL",
        "PRODUTO",
        "OBSERVAÇÃO",
    ],
}

COLS = ["ESCRITÓRIO", "PARTE AUTORA", "PARTE RÉ", "NÚMERO DO PROCESSO", "PRODUTO", "VALOR DA CAUSA", "VALOR DO RISCO ATUALIZADO", "PROBABILIDADE DE PERDA"]
MONETARIO = ["VALOR DA CAUSA", "VALOR DO RISCO ATUALIZADO"]
ABAS_IGNORADAS = {"GRÁFICOS", "ANALYTICS", "DADOS", "TESTE", "RELATÓRIO"}

banco: dict[str, list[pd.DataFrame]] = {"ativas": [], "passivas": []}
hipo: dict[str, list[pd.DataFrame]] = {"ativas": [], "passivas": []}
sec: dict[str, list[pd.DataFrame]] = {"ativas": [], "passivas": []}
trabalhistas: dict[str, list[pd.DataFrame]] = {"BANCO": [], "SERVICE": [], "PROMOTORA": [], "HIPO": []}
outros: list[pd.Series] = []
